import styles from "@/styles/Account.module.css";
import Pic from "@/public/icons/photo.jpg";
import { Fragment, useState } from "react";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import { QRCodeCanvas } from "qrcode.react";
import Modal from "react-modal";
import Image from "next/image";
import CloseIcon from "@/public/icons/close.svg";

export default function account() {
  const [tfaPage, setTfaPage] = useState(1);
  const [openModal, setOpenModal] = useState(false);
  const [toggleTwoFactorAuth, setToggleTwoFactorAuth] = useState(true);

  return (
    <Fragment>
      <Head>
        <title>My account - Noject</title>
      </Head>
      <Navbar showSidebar={true} showBtnDashboard={true} />
      <div className={styles.account}>
        <div className={styles.profileInfo}>
          <img src={Pic.src} alt='Profile Picture' />
          <input
            type='file'
            hidden
            accept='image/*'
            multiple={false}
            onChange={(e) => {
              if (e.target.files[0]) console.log(e.target.files);
            }}
          />
          <button
            onClick={(e) => {
              e.target.previousSibling.click();
            }}>
            Change Picture
          </button>
          <h3>Ivan Krstev</h3>
          <p>ivankrstev246@gmail.com</p>
          <p>Created at: </p>
        </div>
        <div className={styles.changeEmailForm}>
          <label htmlFor='changeEmail'>Change email address:</label>
          <input id='changeEmail' type='email' placeholder='Enter your new email address' />
          <button>Send email link</button>
        </div>
        <div className={styles.changePasswordForm}>
          <h4>Change your password</h4>
          <label htmlFor=''>Current password:</label>
          <input id='' type='password' placeholder='Enter your old password' />
          <label htmlFor=''>New password:</label>
          <input id='' type='password' placeholder='Enter your new password' />
          <label htmlFor=''>Repeat new password:</label>
          <input id='' type='password' placeholder='Reenter your new password' />
          <button>Change password</button>
        </div>
        <div className={styles.twoFactorAuth}>
          <p>
            Two Factor Authentication is {toggleTwoFactorAuth ? "Enabled" : "Disabled"}
            {". "}
            <button className={styles.toggleTwoFactorAuthBtn}>
              {toggleTwoFactorAuth ? "Disable" : "Enable"}
            </button>
          </p>
          <Modal className={styles.twoFactorModal} isOpen={openModal}>
            <div className={styles.scanQrCode}>
              <div className={styles.scanQrCodeHeader}>
                <h3>
                  {toggleTwoFactorAuth
                    ? "Enable two-factor authentication"
                    : "Disable two-factor authentication"}
                </h3>
                <button onClick={() => setOpenModal(false)}>
                  <Image src={CloseIcon} alt='Close Modal' width={30} />
                </button>
              </div>
              {tfaPage === 1 && (
                <Fragment>
                  <div className={styles.qrCodeImg}>
                    <QRCodeCanvas value='F1LPCLXF795RENEH' />
                  </div>
                  <p>
                    Scan the QR code or manually enter the following code:{" "}
                    <span>F1LPCLXF795RENEH</span>
                  </p>
                  <button className={styles.complete2FABtn} onClick={() => setTfaPage(2)}>
                    Continue
                  </button>
                </Fragment>
              )}
              {tfaPage === 2 && (
                <Fragment>
                  <label>Enter the code generated by your authentication app.</label>
                  <input type='text' />
                  <div className={styles.twoFactorFormButtons}>
                    {toggleTwoFactorAuth && (
                      <button
                        style={{
                          backgroundColor: "grey",
                          borderColor: "grey",
                          marginRight: "0.3em",
                        }}
                        className={styles.complete2FABtn}
                        onClick={() => setTfaPage(1)}>
                        Go Back
                      </button>
                    )}
                    <button className={styles.complete2FABtn}>Verify</button>
                  </div>
                </Fragment>
              )}
            </div>
          </Modal>
        </div>
      </div>
    </Fragment>
  );
}
